global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 30s

scrape_configs:
  - job_name: jenkins
    scheme: http
    metrics_path: /prometheus
    static_configs:
      - targets: ["host.docker.internal:8081"]  
        labels:
          service: jenkins
          env: prod

  # Backend PROD (Quarkus)
  - job_name: app-prod
    metrics_path: /q/metrics
    static_configs:
      - targets: ["m2prod-backend-1:8080"]  
        labels:
          service: app-backend-prod
          env: prod

  - job_name: node
    static_configs:
      - targets: ["node-exporter:9100"]
        labels:
          service: host
          env: prod


  
  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]
        labels:
          env: prod

  - job_name: blackbox-http
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://m2prod-frontend-1:80/   
        labels:
          service: app-frontend-prod
          env: prod
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115      
