global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 30s

scrape_configs:
  # --- Jenkins ---
  - job_name: jenkins
    scheme: http
    metrics_path: /prometheus
    static_configs:
      - targets:
          - host.docker.internal:8081
        labels:
          service: jenkins

  # --- App PROD (Quarkus) ---
  - job_name: app-prod
    scheme: http
    metrics_path: /q/metrics
    static_configs:
      - targets:
          - host.docker.internal:8084
        labels:
          service: app-backend-prod
