sonar.projectKey=proyecto-m2-frontend
sonar.projectName=ProyectoM2 :: Frontend
sonar.sourceEncoding=UTF-8

# Fuentes y tests
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.*,**/__tests__/**/*.*,**/tests/**/*.*

# No analices artefactos de build ni coverage
sonar.exclusions=node_modules/**,dist/**,coverage/**,.vite/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info


sonar.coverage.exclusions=src/router/**,src/views/**,src/components/icons/**,src/main.ts,src/App.vue
