# Etapa base con Maven y Java 17
FROM maven:3.9-eclipse-temurin-17

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar todos los archivos del backend al contenedor
COPY . .

# Comando por defecto: iniciar en modo desarrollo
CMD ["mvn", "quarkus:dev"]
