version: "3.9"
name: m2uat
services:
  backend:
    build:
      context: ../backend
    container_name: m2-backend-uat
    environment:
      - QUARKUS_DATASOURCE_DB_KIND=oracle
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:oracle:thin:@oracle-xe:1521/XEPDB1
      - QUARKUS_DATASOURCE_USERNAME=PROYECTO_UAT
      - QUARKUS_DATASOURCE_PASSWORD=UnisUat
      - QUARKUS_HIBERNATE_ORM_DATABASE_DEFAULT_SCHEMA=PROYECTO_UAT
      - QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=update 
      - QUARKUS_HTTP_HOST=0.0.0.0
    networks: [m2-uat-net]

  frontend:
    build:
      context: ..
    container_name: m2-frontend-uat
    depends_on: [backend]
    ports:
      - "8083:80"
    networks: [m2-uat-net]

networks:
  m2-uat-net:
    external: true
