# --- Oracle XE ---
quarkus.datasource.db-kind=oracle
quarkus.datasource.jdbc.url=${DB_URL:jdbc:oracle:thin:@oracle-xe:1521/XEPDB1}
quarkus.datasource.username=${DB_USER:PROYECTO_DEV}
quarkus.datasource.password=${DB_PASSWORD:UnisDev}
# quarkus.datasource.jdbc.driver=oracle.jdbc.OracleDriver
quarkus.hibernate-orm.database.default-schema=${DB_SCHEMA:}

# --- HTTP / CORS ---
quarkus.http.cors=false
quarkus.http.host=0.0.0.0

# --- JWT ---
mp.jwt.verify.publickey.location=META-INF/resources/publicKey.pem
mp.jwt.verify.issuer=quarkus

# --- REST client (parametrizable) ---
quarkus.rest-client.solicitud-hospital-api.url=${HOSPITAL_API_URL:http://localhost:5001/api/solicitudes}

# Dev local
quarkus.test.continuous-testing=enabled

# --- Micrometer / Prometheus ---
quarkus.micrometer.enabled=true
quarkus.micrometer.export.prometheus.enabled=true

# Activa binders útiles
quarkus.micrometer.binder.jvm=true
quarkus.micrometer.binder.system=true
quarkus.micrometer.binder.http-server=true

# El endpoint de métricas es /q/metrics
# Si tienes auth, permite acceso anónimo a /q/metrics
quarkus.http.auth.permission.metrics.paths=/q/metrics
quarkus.http.auth.permission.metrics.policy=permit

